version: "3.9"
services:
  postgres:
    image: postgres
    restart: always
    container_name: aioauth_postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dev
volumes:
  pgdata: {}
