__title__ = "aioauth_fastapi"
__description__ = "aioauth integration for FastAPI."
__url__ = "https://github.com/aliev/aioauth-fastapi"
__version__ = "0.1.1"
__author__ = "Ali Aliyev"
__author_email__ = "ali@aliev.me"
__license__ = "The MIT License (MIT)"
__copyright__ = "Copyright 2021 Ali Aliyev"
