"""Initial migrations

Revision ID: 767eb9eee668
Revises: fa1eae8b783a
Create Date: 2021-09-16 00:05:03.373825

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "767eb9eee668"
down_revision = "fa1eae8b783a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.alter_column("user", "is_superuser", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("user", "is_blocked", existing_type=sa.BOOLEAN(), nullable=True)
    op.create_index(op.f("ix_user_is_active"), "user", ["is_active"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_is_active"), table_name="user")
    op.alter_column("user", "is_blocked", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("user", "is_superuser", existing_type=sa.BOOLEAN(), nullable=False)
    op.drop_column("user", "is_active")
    # ### end Alembic commands ###
