"""Initial migrations

Revision ID: e5e59fb35f30
Revises: d6633986eaab
Create Date: 2021-08-14 00:44:06.773674

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e5e59fb35f30"
down_revision = "d6633986eaab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "authorization_code",
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
    )
    op.create_unique_constraint(None, "authorization_code", ["id"])
    op.create_unique_constraint(None, "client", ["id"])
    op.create_unique_constraint(None, "token", ["id"])
    op.create_unique_constraint(None, "user", ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.drop_constraint(None, "token", type_="unique")
    op.drop_constraint(None, "client", type_="unique")
    op.drop_constraint(None, "authorization_code", type_="unique")
    op.drop_column("authorization_code", "user_id")
    # ### end Alembic commands ###
