# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  ci:
    name: Continuous integration
    runs-on: ubuntu-latest
    env:
      JWT_PUBLIC_KEY: ${{ secrets.JWT_PUBLIC_KEY }}
      JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
      PSQL_DSN: postgresql+asyncpg://postgres:aioauth_fastapi_demo@localhost:5432/aioauth_fastapi_demo
    services:
      postgres:
        image: postgres:14.1
        env:
          POSTGRES_PASSWORD: aioauth_fastapi_demo
          POSTGRES_DB: aioauth_fastapi_demo
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.10.4"
    - name: Install dependencies
      run: |
        make dev-install
        pip install codecov
    - name: Run lint
      run: |
        make lint
    - name: Run tests
      run: |
        make test
    - name: Upload test coverage
      run: codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
